[pytest]
# 用例路径
testpaths = testcases

# 用例文件名规则
python_files = test_*.py

# 类名规则
python_classes = Test*

# 方法名规则
python_functions = test_*

# 命令行参数 👇 这里最有用
addopts = -v --clean-alluredir